version: "3.0"

networks: 
  boilerplate:

services:

  cache:
    container_name: "cache"
    image: redis:alpine
    ports:
      - "6379:6379"
    networks: 
      - boilerplate
    restart: always

  mongodb:
    container_name: "mongodb"
    image: mongo:latest
    ports:
      - "27017:27017"
    networks: 
      - boilerplate
    restart: always

  mysql:
    container_name: "mysql"
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    networks:
      - boilerplate
    restart: always

  ava:
    build: .
    command: ["./wait_for_it.sh", "mysql:3306", "--", "echo", "**** Starting Tests ***"]
    container_name: "ava"
    depends_on:
      - cache
      - mongodb
      - mysql
    environment: 
      - REDIS_URL=cache
      - MONGO_URI=mongodb
      - MYSQL_URL=mysql
    ports:
      - "3001:3001"
      - "8443:8443"
    networks: 
      - boilerplate    